version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ResumeProcessorApp"
s3_bucket = "aws-lambda-default"
s3_prefix = "ResumeProcessorApp"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
